### ISSUE TITLE
dvws walkthrough guid

### ISSUE THREAD

**Issue by rfma** [snoopysecurity/Public#1]
the dvws walkthrough guide(https://github.com/snoopysecurity/Public/blob/master/img/DVWS-_Understanding_Common_Web_Service_Vulnerabilies-V0.2.pdf) can not download, could you please help me?  I am a newbie to learn dvws.

 thank you!!

**Comment by snoopysecurity** [comment]
Hey @rfma apologies for the delayed reply, you can find it here: https://github.com/snoopysecurity/Public/blob/master/Attacking%20Damn%20Vulnerable%20Web%20Services.pdf

but DVWS PHP is really outdated, and you should be using https://github.com/snoopysecurity/dvws-node, there is no guide for dvws-node so far but if you have any questions, feel free to open a GItHub Issue

**Comment by SysAdminZ00** [comment]
5/2/2026

404 - page not found
The 

master
 branch of 

Public
 does not contain the path 

Attacking Damn Vulnerable Web Services.pdf.

**Comment by snoopysecurity** [comment]
Hi @SysAdminZ00 use https://github.com/snoopysecurity/dvws-node, dvws (php version) and its guide Attacking Damn Vulnerable Web Services.pdf. isnt supported anymore
